language: groovy
sudo: false
cache:
  directories:
  - "$HOME/.gradle/caches"
  - "$HOME/.gradle/wrapper"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
jdk:
- oraclejdk8
install: true
script: "./travis-build.sh"
env:
  global:
  - GIT_NAME="Puneet Behl"
  - GIT_EMAIL="behl4485@gmail.com"
  - secure: fXV0rgYKrs/LDWRBanf61pWB3qmRxY9Jl7u3FlBtz3v7qXE8jaQ0bOCMFAN6HivbtGbEQHRvua7ZyfmyUORJ93rTSmB+MKbp7sNnvGFJKxzd/CGqXHUZDAi9MV2sLIzEZGjyTmR5nF3xeUipdNzghRD4YJVVY7TUv6dZ1+2hgrM=
  - secure: pOYRk1tUDCaB9Egar8CA9sNEksSbBWy2GZzQIBpx35E5vuxn0EowsfsfHVBGA2fa3trh4ljI+81b7XZwnTdM3HQa8MNJzSoUyImox+s0nXAP/dI5w5xIiOUj0p9hACGHGmU/08OC8YZB6WUYkqr+WbJdBh8kvxp1Fmp0lbGhzPA=
  - secure: TAgXu0/x53T8/x0WnT2dGPf2k+k3E0dsIP/EjnRON0E3CyDDCxpBzTiK835TcKTxqgqkQrkwGpGD5uzny7YH+tXAYvNHlWonOnkAptxwx8KJMgeKdXUjkyLbaBgBhsvUZbmpaNQpAcdcOVvhR3gJaVQ+IVspZnLq8kVJ6+8z8F0=
  - secure: sRzwiIJLvkgu/lAtCCs3rGBJKvO63OMvLZTpfXhRteHZ/Ik7JdrNAvOJ/Qo89Of29TrZSFTk82j4T3dtJuqwfhRAydeTnIMRZlzt9l5RSUd2d3ehBvPOsQKk5WJVr2CBhrZPce5qxa5AolV2594Y/eifdnYEDrF9/vzOC23GsA0=
  - secure: WN1vcBGO+0XOcs3s9AtzObW2nGQoM/EqeGKF4E3F7UycrBVCnlfWxGjNJqdbWFJSPU7s5sdxmXgDKVY0JGWcl5lJXAPz9EPTfhYAdOdwdjFh/hhLgX7Hihfe277eJBQFX7nWbIS6ZV/NAeYCjOfyZ6kVbmG7NPPq9WtStP0SVbI=
  - secure: sZVx0SySHyDTFckKiCPy55/75bP36AmxReZ1yb9S0dH35X6xMQE/f2AxbRPqtDwFUlL5qYXUq45G24pHlmLpOlNA45wNw4jB4JxwOHHD+C99aw4CwAKSYOEsfX44LljYyJUieLb+/zCY82ieXWOD1bSV74DDO9+zj9v3g6Gr8xg=
  - secure: NIbUH7lPcdOW2+5l97f6bOHjsOOHQTF7P41YgsHKRh2QjcpoSDRlPNcNVBTTl4F9u/DXMnm8FNQTX1pHIxu8TLRJsbPoJ2q41DXpE08BRYKotze+a6sGY3q02uzYiKnOMIrmPzNNSRypdx2ICtUpH8ZCqgGsUaUKKsMHGoGfYn0=
